// Code generated by goagen v1.3.0, DO NOT EDIT.
//
// API "cellar": Application User Types
//
// Command:
// $ goagen
// --design=BorysDrozhak/GOA_start/design
// --out=$(GOPATH)/src/BorysDrozhak/GOA_start
// --version=v1.3.0

package app
